import { Router, Request, Response, NextFunction } from 'express';
import Category from '../models/Category';
import { authenticateAdmin } from '../middleware/authMiddleware';

const router = Router();

// GET /api/categories — list all categories
router.get('/', async (_req: Request, res: Response, next: NextFunction) => {
  try {
    const categories = await Category.find().sort({ name: 1 });
    res.json(categories);
  } catch (error) {
    next(error);
  }
});

// GET /api/categories/:id — get single category
router.get('/:id', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const category = await Category.findById(req.params.id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    res.json(category);
  } catch (error) {
    next(error);
  }
});

// POST /api/categories — create category (admin)
router.post('/', authenticateAdmin, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { name, description, image, isActive } = req.body;

    const existing = await Category.findOne({ name: { $regex: new RegExp(`^${name}$`, 'i') } });
    if (existing) {
      return res.status(400).json({ message: 'Category with this name already exists' });
    }

    const category = new Category({ name, description, image, isActive });
    await category.save();
    res.status(201).json(category);
  } catch (error) {
    next(error);
  }
});

// PUT /api/categories/:id — update category (admin)
router.put('/:id', authenticateAdmin, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { name, description, image, isActive } = req.body;

    // Check for duplicate name
    if (name) {
      const existing = await Category.findOne({
        name: { $regex: new RegExp(`^${name}$`, 'i') },
        _id: { $ne: req.params.id },
      });
      if (existing) {
        return res.status(400).json({ message: 'Category with this name already exists' });
      }
    }

    const category = await Category.findById(req.params.id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }

    if (name) {
      category.name = name;
      // Slug will be auto-generated by pre-save hook
    }
    if (description !== undefined) category.description = description;
    if (image !== undefined) category.image = image;
    if (isActive !== undefined) category.isActive = isActive;

    await category.save();
    res.json(category);
  } catch (error) {
    next(error);
  }
});

// DELETE /api/categories/:id — delete category (admin)
router.delete('/:id', authenticateAdmin, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const category = await Category.findByIdAndDelete(req.params.id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    res.json({ message: 'Category deleted' });
  } catch (error) {
    next(error);
  }
});

export default router;
